### ISSUE TITLE
how does it works?

### ISSUE THREAD

**Issue by braguzz** [dkd/typo3-ext-cmis-fal#1]
Hi can You tell me how does it works,

In one of my old project I used atol_cmis ext to render a tree from cmis repository starting from a folder.
result is like this page 
http://www.provincia.livorno.it/canali/caccia-e-pesca/modulistica/

the problem is that is really slow

Can  your ext  renders a tree?

**Comment by sascha-egerer** [comment]
Hi,
we use the php-cmis-client lib (which is also developed by us) for the communication with the CMIS Server. This is basically a port of the Java OpenCMIS implementation. 
The first question is if you really need the FAL stuff. That gives you the possibility to also manage the documents in TYPO3. But if you just need a listing this is ont required and you may better write you own extension that uses the CMIS library. 
Rendering a tree should not be a problem as you have just to fetch the children of a folder (recursively).

Could you explain what excactly is needed for you requirements?

**Comment by braguzz** [comment]
The idea is have two kind of web content users:
_Typo3 users,  that  have to know typo3 be and we have to teach the t3 ecc
-alfresco users,  that use alfresco stare to put documents in  folders, and
that documents are processed by alfresco and magically showed in web.

See this http://www.provincia.livorno.it/menu/menu-footer/credits/

And this http://www.provincia.livorno.it/canali/caccia-e-pesca/modulistica/
For an example.

The problem of render a tree recursively is solved,  but is drammatically
slow.
Solution should use of some ajax to dinamically build the tree,  but
sincerelly I trend to do that, but I not a real programmer, and I never
solved the problem...
 Il 24/apr/2015 17:28, "Sascha Egerer" <notifications@github.com> ha
scritto:

**Comment by sascha-egerer** [comment]
I've just created a gist to list the Children of a folder.
That can be easyliy adjusted. In this version it lists the children of the Root folder.
You can simply add a action that get's an optional Folder Id and if it is not set the root folder will be used.
https://gist.github.com/sascha-egerer/0fa5d55869c0f379d9a9

**Comment by braguzz** [comment]
It lists all the tree? And with ajax asincrono retrovie?
Il 24/apr/2015 18:52, "Sascha Egerer" <notifications@github.com> ha scritto:

**Comment by sascha-egerer** [comment]
No it just lists the content of the Root folder. But you can also load an Object over the Session which means you can pass the cmis folder id over Ajax to the Action which then returns you the children of that (sub) folder. 
Should be pretty easy (for a coder)

**Comment by braguzz** [comment]
I have to find a coder,  or study more (but I cant find the time...)

I cant Believe that im the only one interesse in this problem..
Il 24/apr/2015 19:12, "Sascha Egerer" <notifications@github.com> ha scritto:

**Comment by sascha-egerer** [comment]
If you wan't you can contact us at info@dkd.de

I'll close this issue now as it is not related to cmis_fal

**Comment by braguzz** [comment]
Ok thank you.
Il 24/apr/2015 19:24, "Sascha Egerer" <notifications@github.com> ha scritto:
