### ISSUE TITLE
t3 7.2

### ISSUE THREAD

**Issue by braguzz** [dkd/typo3-ext-cmis-fal#2]
trying to install it in T3 7.2 but I got this error while enable ext:

Fatal error: Declaration of Dkd\CmisFal\Driver\CMISFilesystemDriver::getFilesInFolder() must be compatible with TYPO3\CMS\Core\Resource\Driver\DriverInterface::getFilesInFolder($folderIdentifier, $start = 0, $numberOfItems = 0, $recursive = false, array $filenameFilterCallbacks = Array, $sort = '', $sortRev = false) in /data/www5/bootstrap_package/typo3conf/ext/cmis_fal/Classes/Driver/CMISFilesystemDriver.php on line 23

**Comment by dkd-dobberkau** [comment]
Currently TYPO3 6.2 only.

**Comment by sascha-egerer** [comment]
Thats correct. We currently support only TYPO3 6.2. 
In TYPO3 7.x are many breaking changes escpecially with the interfaces what whould require a complete seperate version of this driver. So we will keep on 6.2 only until the driver has it's full functionality.

**Comment by braguzz** [comment]
ok thanks
